# Site settings
author: Adeja Lendor
title: Adeja Lendor's Software Engineering Blog
header-img: img/home-bg.png
email: alendor6@gmail.com
copyright_name: Adeja Lendor
description: > # this means to ignore newlines until "baseurl:"
  A journey into the beginnings of a Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Alendor22

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
